# Generated by Django 5.0.6 on 2024-05-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vaccine name ')),
                ('description', models.TextField()),
                ('number_of_dose', models.IntegerField(default=1)),
                ('interval', models.IntegerField(default=0, help_text='Please provide the interval')),
                ('storage_temprature', models.IntegerField(blank=True, help_text='Please provide temprature ', null=True)),
                ('minimum_age', models.IntegerField(default=0)),
            ],
        ),
    ]
